### ISSUE TITLE
Merge newlib 2.4.0

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-newlib#3]
I've rebase newlib to 2.4, it's include git log after 2016/8 which cherry-pick by manual from https://github.com/riscv/riscv-gnu-toolchain and it's also include 2 bug fix patch, can you pull the branch into this repo, and of cause I've run regression test :)

And my next plan is let this repo become a sub-moudle of riscv-gnu-toolchain.
https://github.com/kito-cheng/riscv-newlib

@palmer-dabbelt  @aswaterman

**Comment by palmer-dabbelt** [comment]
Thanks Kito.  We're at the RISC-V workshop today, can you submit a pull request with your stuff in it (or probably two: one against riscv-gnu-toolchain and one against riscv-newlib)?  I can't find specifically which branch your fixes are on.

**Comment by kito-cheng** [comment]
riscv-newlib-2.4.0 branch, and I need your help since there is lots of conflict if using pull request since the code base is different, maybe you can just pull my kito-cheng/riscv-newlib/riscv-newlib-2.4.0 and push into riscv/riscv-newlib?
https://github.com/kito-cheng/riscv-newlib/tree/riscv-newlib-2.4.0

**Comment by kito-cheng** [comment]
riscv-gnu-toolchain part will send PR after newlib 2.4 merge done

**Comment by kito-cheng** [comment]
ping @palmer-dabbelt

**Comment by palmer-dabbelt** [comment]
Sorry, I'm going to look this I just have some things this morning.

**Comment by kito-cheng** [comment]
thanks :)
