### ISSUE TITLE
libnosys is missing leading underscores on symbol names

### ISSUE THREAD

**Issue by jstraus59** [riscv/riscv-newlib#36]
The symbols in libnosys need leading underscores added in order to be compatible with the naming used in newlib. See discussion with @ilg-ul [here](https://forums.sifive.com/t/gnu-mcu-eclipse/659/16) for details, including a proposed fix from @jim-wilson  [here](https://forums.sifive.com/t/gnu-mcu-eclipse/659/19?)

**Comment by jim-wilson** [comment]
This was already fixed upstream in December, before the newlib-3.0.0 release.  We already have an approved pull request for riscv-gnu-toolchain to use the newlib-3.0.0 branch, so this will get fixed shortly.  Though I see that riscv-newlib still says that the master branch is newlib-2.5.0.  That should be fixed.

**Comment by kito-cheng** [comment]
Default branch is update to `newlib-3.0.0` and riscv-gnu-toolchain also updated.

@jim-wilson thanks :)
