### ISSUE TITLE
atexit() can only register 31 functions

### ISSUE THREAD

**Issue by PkmX** [riscv/riscv-newlib#6]
Both C and POSIX requires at least 32 functions to be registered by `atexit()`, but RISC-V already uses one for `__libc_fini_array` in libgloss, so only 31 functions can be registered by users.

```c
#include <stdlib.h>
#include <stdio.h>

void fn(void) {}

int main(void) {
    for (int i = 0; i < 32; ++i) {
        printf("%d: atexit(fn) = %d\n", i, atexit(fn));
    }

    return 0;
}
```

Sample output:

```
0: atexit(fn) = 0
1: atexit(fn) = 0
2: atexit(fn) = 0
...
30: atexit(fn) = 0
31: atexit(fn) = -1
```

Perhaps we should use other mechanisms to call `__libc_fini_array` or increase `_ATEXIT_SIZE` to compensate for that.

**Comment by aswaterman** [comment]
Let's do the simple thing and increase _ATEXIT_SIZE.  Can you submit a PR?

**Comment by kito-cheng** [comment]
This issue also happen on arm and aarch64 port too, btw I prefer do not modify generic code.

**Comment by palmer-dabbelt** [comment]
It also looks like this has been talked about on the newlib mailing list (in 2006), and there's a dynamic _ATEXIT_SIZE handling mechanism.

https://www.sourceware.org/ml/newlib/2006/msg00207.html
http://git.net/ml/lib.newlib/2006-08/msg00085.html

I'm going to close this, as it's an issue with the upstream port.  If we're mis-understanding something feel free to re-open the bug.
